---
- hosts: web
  remote_user: root
  gather_facts: true

  vars_files:
    - vars/mysql.yml
    - vars/apache.yml
    - vars/php.yml
    - vars/firewall.yml
    - vars/nodejs.yml
    - vars/certbot.yml

  vars:
    - update_apt_cache: yes
    - php_version: '7.3'

#  pre_tasks:
#    - name: Wait for port 22 to become available.
#      local_action: "wait_for port=22 host={{ ansible_host }}"
#    - name: Update apt cache if needed.
#      apt: update_cache=yes cache_valid_time=3600

  roles:
    - role: geerlingguy.firewall
    - role: geerlingguy.ntp
    - role: geerlingguy.mysql
    - role: geerlingguy.apache
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql
    - role: custom_dependencies
#    - role: geerlingguy.composer
#    - role: geerlingguy.redis
#    - role: geerlingguy.nodejs
#    - role: geerlingguy.certbot
#    - role: ocha.yarn