version: "3.9"

services:
  app:
    build:
      args:
        user: '${SYSTEM_USER}'
        uid: '${SYSTEM_UID}'
      context: ./bin/php
      dockerfile: Dockerfile
    image: '${PROJECT_NAME}'
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - '${DOCUMENT_ROOT}:/var/www'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - main
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      - main
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '${HOST_MACHINE_UNSECURE_HOST_PORT}:80'
    volumes:
      - '${DOCUMENT_ROOT}:/var/www'
      - ./config/nginx:/etc/nginx/conf.d
    networks:
      - main
#  node:
#    image: node:12
#    container_name: node
#    restart: 'no'
#    ports:
#      - 3030:3030
#    networks:
#      - main
#    volumes:
#      - '${DOCUMENT_ROOT}:/usr/app'
#    working_dir: /usr/app
networks:
  main:
    driver: bridge